### ISSUE TITLE
v0.22.0: RangeError: Maximum call stack size exceeded?

### ISSUE THREAD

**Issue by tony-kerz** [xojs/xo#347]
[this project](https://github.com/the-watchmen/material-ui-data-table/commit/11dfd39eac43360060756532fcfaf3064d5e42b3) incurs the below error when bumping from `0.21.1` -> `0.22.0`:

```
~/g/material-ui-data-table   tk/mui-1 *  yarn xo                                    33.9s  Tue Aug  7 07:29:25 2018
yarn run v1.9.2
$ xo
RangeError: Maximum call stack size exceeded
    at cloneObject (/Users/tony/git/material-ui-data-table/node_modules/espurify/lib/clone-ast.js:44:26)
    at cloneNodeOrObject (/Users/tony/git/material-ui-data-table/node_modules/espurify/lib/clone-ast.js:21:20)
    at cloneOf (/Users/tony/git/material-ui-data-table/node_modules/espurify/lib/clone-ast.js:61:24)
    at cloneObject (/Users/tony/git/material-ui-data-table/node_modules/espurify/lib/clone-ast.js:49:26)
    at cloneNodeOrObject (/Users/tony/git/material-ui-data-table/node_modules/espurify/lib/clone-ast.js:21:20)
    at cloneOf (/Users/tony/git/material-ui-data-table/node_modules/espurify/lib/clone-ast.js:61:24)
    at cloneObject (/Users/tony/git/material-ui-data-table/node_modules/espurify/lib/clone-ast.js:49:26)
    at cloneNodeOrObject (/Users/tony/git/material-ui-data-table/node_modules/espurify/lib/clone-ast.js:21:20)
    at cloneOf (/Users/tony/git/material-ui-data-table/node_modules/espurify/lib/clone-ast.js:61:24)
    at cloneObject (/Users/tony/git/material-ui-data-table/node_modules/espurify/lib/clone-ast.js:49:26)
```

**Comment by sindresorhus** [comment]
// @twada

**Comment by twada** [comment]
@tony-kerz 
This problem is fixed by [espurify 1.8.1](https://github.com/estools/espurify/blob/master/CHANGELOG.md#181-2018-07-10). Would you clean-reinstall xo again?

**Comment by twada** [comment]
@tony-kerz Thanks. It seems that `espurify@1.7.0` is coming from your `yarn.lock` file. Would you update it too?

**Comment by tony-kerz** [comment]
doh, forgot `yarn.lock` 😊 regenerating that resolved this issue, thanks guys!
