### ISSUE TITLE
Error: Failed to load config "xo-typescript" to extend from.

### ISSUE THREAD

**Issue by fregante** [xojs/xo#454]
I'm having the same issue reported by Sindre here: https://github.com/xojs/xo/pull/426#issuecomment-587314458

```js
Error: Failed to load config "xo-typescript" to extend from.
Referenced from: BaseConfig
    at configMissingError (./node_modules/eslint/lib/cli-engine/config-array-factory.js:265:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (./node_modules/eslint/lib/cli-engine/config-array-factory.js:826:23)
    at ConfigArrayFactory._loadExtends (./node_modules/eslint/lib/cli-engine/config-array-factory.js:731:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (./node_modules/eslint/lib/cli-engine/config-array-factory.js:660:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (./node_modules/eslint/lib/cli-engine/config-array-factory.js:596:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at createConfigArray (./node_modules/eslint/lib/cli-engine/config-array-factory.js:340:25)
    at ConfigArrayFactory.create (./node_modules/eslint/lib/cli-engine/config-array-factory.js:395:16)
    at createBaseConfigArray (./node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:86:48)
```

This also happens after clearing `~/.xo-cache` and `rm -rf node_modules package-lock.json && npm i`

## Config

```json
{
	"xo": {
		"envs": [
			"browser"
		],
		"rules": {
			"@typescript-eslint/no-unnecessary-type-assertion": "off"
		}
	},
	"devDependencies": {
		"@sindresorhus/tsconfig": "^0.7.0",
		"browserify": "^16.2.2",
		"esmify": "^2.1.1",
		"npm-run-all": "^4.1.3",
		"tape": "^4.10.1",
		"tape-run": "^5.0.0",
		"typescript": "^3.8.3",
		"xo": "^0.28.3"
	}
}
```

## Versions

macOS 10.15
Node v13.8.0
npm 6.13.6
xo 0.28.3

**Comment by fregante** [comment]
This fixed it, but it shouldn't be necessary:

```sh
npm i -D eslint-config-xo-typescript @typescript-eslint/parser @typescript-eslint/eslint-plugin
```

**Comment by fregante** [comment]
And now I can no longer reproduce. Neat.
