### ISSUE TITLE
Error is displayed twice on package.json JSONError

### ISSUE THREAD

**Issue by OmgImAlexis** [xojs/xo#455]
```shell
➜  core git:(master) ✗ xo app/plugin-manager.ts
JSONError: JSON Error in /Users/xo/code/unraid/core/package.json: 

  162 |                         "import/resolver": {
  163 |       "node": {},
> 164 |     },
      |     ^
  165 | 			"jsdoc": {
  166 | 				"preferredTypes": {
  167 | 					"object": "Object"

Unexpected token } in JSON at position 4858 while parsing near '...    "node": {},    },			"jsdoc": {			...' 

  162 |                         "import/resolver": {
  163 |       "node": {},
> 164 |     },
      |     ^
  165 | 			"jsdoc": {
  166 | 				"preferredTypes": {
  167 | 					"object": "Object"

    at module.exports (/Users/xo/code/unraid/core/node_modules/cosmiconfig/node_modules/parse-json/index.js:29:21)
    at Object.loadJson (/Users/xo/code/unraid/core/node_modules/cosmiconfig/dist/loaders.js:28:20)
    at Explorer.loadPackageProp (/Users/xo/code/unraid/core/node_modules/cosmiconfig/dist/ExplorerBase.js:82:44)
    at Explorer.loadFileContent (/Users/xo/code/unraid/core/node_modules/cosmiconfig/dist/Explorer.js:107:32)
    at Explorer.createCosmiconfigResult (/Users/xo/code/unraid/core/node_modules/cosmiconfig/dist/Explorer.js:112:36)
    at runLoad (/Users/xo/code/unraid/core/node_modules/cosmiconfig/dist/Explorer.js:126:33)
    at async cacheWrapper (/Users/xo/code/unraid/core/node_modules/cosmiconfig/dist/cacheWrapper.js:16:18)
    at async Promise.all (index 0)
    at async Object.lintFiles (/Users/xo/code/unraid/core/node_modules/xo/index.js:100:23)
    at async /Users/xo/code/unraid/core/node_modules/xo/cli-main.js:171:18
```

**Comment by fregante** [comment]
Gonna assume this isn't happening after eslint v9 and xo v1
