### ISSUE TITLE
Error: The flag --env can only be set once.

### ISSUE THREAD

**Issue by Gaspacchio** [xojs/xo#495]
XO `v0.33.0` with multiple `env` flags crashes and says that the `env` flag can only be set once. It used to work in `v0.32.1` and the documentation says ["Environment preset  [Can be set multiple times]"](https://github.com/xojs/xo#usage).

Is this behavior normal or is that a bug?

```cli
$ yarn run lint
yarn run v1.22.5
$ xo **/*.js --fix --env=browser --env=node
C:\Users\Gaspard\Documents\Code\crouzet\pricing\node_modules\meow\index.js:93
                        throw new Error(`The flag --${flagKey} can only be set once.`);
                        ^

Error: The flag --env can only be set once.
    at validateFlags (C:\Users\Gaspard\Documents\Code\crouzet\pricing\node_modules\meow\index.js:93:10)
    at meow (C:\Users\Gaspard\Documents\Code\crouzet\pricing\node_modules\meow\index.js:193:2)       
    at Object.<anonymous> (C:\Users\Gaspard\Documents\Code\crouzet\pricing\node_modules\xo\cli-main.js:11:13)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\Gaspard\Documents\Code\crouzet\pricing\node_modules\xo\cli.js:14:2)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Config

- xo `0.33.0`
- yarn `1.22.5`

**Comment by Gaspacchio** [comment]
Thanks 🙏
