### ISSUE TITLE
Error: Failed to load config "xo" to extend from

### ISSUE THREAD

**Issue by wooorm** [xojs/xo#504]
I cannot reproduce this locally, but fresh installs of Node, npm, etc, on Travis and GitHub Actions started failing recently:

On Travis (https://travis-ci.org/github/micromark/micromark/jobs/740973140#L257)

```
Error: Failed to load config "xo" to extend from.
258Referenced from: BaseConfig
259    at configMissingError (/home/travis/build/micromark/micromark/node_modules/@eslint/eslintrc/lib/config-array-factory.js:289:9)
260    at ConfigArrayFactory._loadExtendedShareableConfig (/home/travis/build/micromark/micromark/node_modules/@eslint/eslintrc/lib/config-array-factory.js:877:23)
261    at ConfigArrayFactory._loadExtends (/home/travis/build/micromark/micromark/node_modules/@eslint/eslintrc/lib/config-array-factory.js:780:25)
262    at ConfigArrayFactory._normalizeObjectConfigDataBody (/home/travis/build/micromark/micromark/node_modules/@eslint/eslintrc/lib/config-array-factory.js:719:25)
263    at _normalizeObjectConfigDataBody.next (<anonymous>)
264    at ConfigArrayFactory._normalizeObjectConfigData (/home/travis/build/micromark/micromark/node_modules/@eslint/eslintrc/lib/config-array-factory.js:664:20)
265    at _normalizeObjectConfigData.next (<anonymous>)
266    at ConfigArrayFactory.create (/home/travis/build/micromark/micromark/node_modules/@eslint/eslintrc/lib/config-array-factory.js:459:16)
267    at createBaseConfigArray (/home/travis/build/micromark/micromark/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:98:48)
268    at new CascadingConfigArrayFactory (/home/travis/build/micromark/micromark/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:234:30)
269
```

On Actions: https://github.com/micromark/micromark/runs/1357272781?check_suite_focus=true#step:5:34

```
Error: Failed to load config "xo" to extend from.
35
Referenced from: BaseConfig
36
    at configMissingError (/home/runner/work/micromark/micromark/node_modules/@eslint/eslintrc/lib/config-array-factory.js:289:9)
37
    at ConfigArrayFactory._loadExtendedShareableConfig (/home/runner/work/micromark/micromark/node_modules/@eslint/eslintrc/lib/config-array-factory.js:877:23)
38
    at ConfigArrayFactory._loadExtends (/home/runner/work/micromark/micromark/node_modules/@eslint/eslintrc/lib/config-array-factory.js:780:25)
39
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/home/runner/work/micromark/micromark/node_modules/@eslint/eslintrc/lib/config-array-factory.js:719:25)
40
    at _normalizeObjectConfigDataBody.next (<anonymous>)
41
    at ConfigArrayFactory._normalizeObjectConfigData (/home/runner/work/micromark/micromark/node_modules/@eslint/eslintrc/lib/config-array-factory.js:664:20)
42
    at _normalizeObjectConfigData.next (<anonymous>)
43
    at ConfigArrayFactory.create (/home/runner/work/micromark/micromark/node_modules/@eslint/eslintrc/lib/config-array-factory.js:459:16)
44
    at createBaseConfigArray (/home/runner/work/micromark/micromark/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:98:48)
45
    at new CascadingConfigArrayFactory (/home/runner/work/micromark/micromark/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:234:30)
```

I am guessing this has something to do with npm@7’s peer dep resolving? 🤔

**Comment by wooorm** [comment]
I can now reproduce it locally on npm 7.0.8

**Comment by wooorm** [comment]
This seems to be caused by `sonarjs` being used too, which does not allow eslint 7 as a peer dep:

https://github.com/SonarSource/eslint-plugin-sonarjs/blob/5679fbcc76f45fc40c3392a8a1b4e61495e0a16e/package.json#L27

...which conflicts with xo wanting v7:

https://github.com/xojs/eslint-config-xo/blob/master/package.json#L63

**Comment by sindresorhus** [comment]
That sounds like a npm bug.

**Comment by wooorm** [comment]
Yeah! Might be fine to close it, but maybe other folks will start running into it.

A “fix” might be to add an eslint peer-dep higher up?

**Comment by sindresorhus** [comment]
But ESLint is already a dependency.

**Comment by wooorm** [comment]
...d’oh, of course. Well, that’s *really* weird 🤔

OK: another idea on why this might’ve happened: ESLint 6 and xo were placed in `./node_modules/`, and ESLint 7 and `eslint-config-xo` in `./node_modules/xo/node_modules`. ESLint’s config parser, `@eslint/eslintrc`, is new and only in ESLint 7, so because it can’t conflict it’s placed in `./node_modules/`. Hence the error because it can’t find `eslint-config-xo`?

**Comment by fregante** [comment]
I occasionally have this bug when adding/removing dependencies. Usually deleting node_modules and the lock fixes it, but recently the error persisted until I updated all of the dependencies and tried again.

**Comment by fregante** [comment]
Merging into https://github.com/xojs/xo/issues/404
