### ISSUE TITLE
Yarn 2 and xo 0.41.0

### ISSUE THREAD

**Issue by mbround18** [xojs/xo#575]
yarn: 2.4.2
xo: 0.41.0
node: v14.17.0

Yarn using yarn 2 pnpify

```sh
(node:14776) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/mnt/c/Users/micha/develop/showcase-yourself/.yarn/cache/xo-npm-0.41.0-9a444cd5ea-465ecea7c2.zip/node_modules/xo/cli.js:2
import getStdin from 'get-stdin';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:984:16)
    at Module._compile (internal/modules/cjs/loader.js:1032:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.external_module_.Module._load (/mnt/c/Users/micha/develop/showcase-yourself/.pnp.js:24631:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

reproduction steps: 

1. Switch to yarn 2 via `yarn set version berry`
2. Install xo `yarn add -D xo`
3. Run xo `yarn xo`

**Comment by sindresorhus** [comment]
Open an issue on Yarn 2. This package works perfectly fine with npm. Yarn 2 is known to create a lot of incompatibilities, it's its job to fix them.
