### ISSUE TITLE
Support for Typescript v5 `extends` array

### ISSUE THREAD

**Issue by yorch** [xojs/xo#711]
Typescript v5 now [supports multiple base configurations](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#supporting-multiple-configuration-files-in-extends) through `extends` as an array.

Unfortunately `xo` throws an error as it expects to be a string:

```sh
❯ yarn lint
TypeError [ERR_INVALID_ARG_TYPE]: The "request" argument must be of type string. Received an instance of Array
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at Function.resolve (node:internal/modules/cjs/helpers:115:5)
    at recursiveBuildTsConfig (file:///Users/user/project/node_modules/xo/lib/options-manager.js:652:22)
    at handleTSConfig (file:///Users/user/project/node_modules/xo/lib/options-manager.js:181:28)
    at async mergeWithFileConfig (file:///Users/user/project/node_modules/xo/lib/options-manager.js:140:13)
    at async parseOptions (file:///Users/user/project/node_modules/xo/lib/options-manager.js:587:51)
    at async Promise.all (index 2)
    at async getOptionGroups (file:///Users/user/project/node_modules/xo/lib/options-manager.js:603:21)
    at async Object.lintFiles (file:///Users/user/project/node_modules/xo/index.js:78:17)
```

**Comment by yorch** [comment]
Thanks!
