### ISSUE TITLE
XO seems to not play well with Typescript's array `extends`

### ISSUE THREAD

**Issue by ajotaos** [xojs/xo#736]
It seems that XO is not supporting when using an extends in array form. If I switch it to string form, it works.

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Array
Occurred while linting /Users/alvaro/Developer/Repositories/mouseion/sst.config.ts:2
Rule: "import/no-cycle"
    at new NodeError (node:internal/errors:406:5)
    at validateString (node:internal/validators:162:11)
    at Object.join (node:path:1175:7)
    at loadTsconfig (/Users/alvaro/Developer/Repositories/mouseion/node_modules/.pnpm/tsconfig-paths@3.14.2/node_modules/tsconfig-paths/lib/tsconfig-loader.js:93:39)
    at loadSyncDefault (/Users/alvaro/Developer/Repositories/mouseion/node_modules/.pnpm/tsconfig-paths@3.14.2/node_modules/tsconfig-paths/lib/tsconfig-loader.js:40:18)
    at tsConfigLoader (/Users/alvaro/Developer/Repositories/mouseion/node_modules/.pnpm/tsconfig-paths@3.14.2/node_modules/tsconfig-paths/lib/tsconfig-loader.js:26:22)
    at readTsConfig (/Users/alvaro/Developer/Repositories/mouseion/node_modules/.pnpm/eslint-plugin-import@2.27.5_@typescript-eslint+parser@6.10.0_eslint-import-resolver-webpack@0.13.8_eslint@8.53.0/node_modules/eslint-plugin-import/lib/ExportMap.js:818:528)
    at isEsModuleInterop (/Users/alvaro/Developer/Repositories/mouseion/node_modules/.pnpm/eslint-plugin-import@2.27.5_@typescript-eslint+parser@6.10.0_eslint-import-resolver-webpack@0.13.8_eslint@8.53.0/node_modules/eslint-plugin-import/lib/ExportMap.js:821:277)
    at ExportMap.parse (/Users/alvaro/Developer/Repositories/mouseion/node_modules/.pnpm/eslint-plugin-import@2.27.5_@typescript-eslint+parser@6.10.0_eslint-import-resolver-webpack@0.13.8_eslint@8.53.0/node_modules/eslint-plugin-import/lib/ExportMap.js:808:317)
    at ExportMap.for (/Users/alvaro/Developer/Repositories/mouseion/node_modules/.pnpm/eslint-plugin-import@2.27.5_@typescript-eslint+parser@6.10.0_eslint-import-resolver-webpack@0.13.8_eslint@8.53.0/node_modules/eslint-plugin-import/lib/ExportMap.js:807:201)
```

I'm using Node LTS 20, pnpm, typescript 5.2 and the latest xo

**Comment by tlan16** [comment]
I got same issue with node 20 esm

**Comment by fregante** [comment]
The issue comes from https://github.com/import-js/eslint-plugin-import, please report it there
