### ISSUE TITLE
Upgrade `eslint-plugin-n` to support latest Node.js environment

### ISSUE THREAD

**Issue by abiriadev** [xojs/xo#752]
## Problem

The `eslint-plugin-n` package recently [published v17.0.0](https://github.com/eslint-community/eslint-plugin-n/releases/tag/v17.0.0) which includes a rewrite of legacy code. And [one of the deleted code](https://github.com/eslint-community/eslint-plugin-n/blob/ec5badbca03b8e88c594757e4d5c391370727892/lib/converted-esm/import-meta-resolve.js#L555-L561) called `new fs.Stats`, which [has been deprecated since Node.js v22.0.0](https://nodejs.org/docs/latest/api/all.html#all_deprecations_dep0180-fsstats-constructor).

https://github.com/xojs/xo/blob/ee9f0a3d72d55df098fc321c4d54a1ea3804e226/package.json#L72

However, XO still requires version `16.x` of `eslint-plugin-n`, as a result, you see that a runtime error occurs when running XO with Node.js v22 or higher:

```ps1
$ NODE_OPTIONS=--trace-deprecation node ./node_modules/xo/cli.js --fix

(node:225746) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
    at tryStatSync (/home/abiria/lab/seia/node_modules/.pnpm/eslint-plugin-n@16.6.2_eslint@8.57.0/node_modules/eslint-plugin-n/lib/converted-esm/import-meta-resolve.js:559:12)
    at packageResolve (/home/abiria/lab/seia/node_modules/.pnpm/eslint-plugin-n@16.6.2_eslint@8.57.0/node_modules/eslint-plugin-n/lib/converted-esm/import-meta-resolve.js:1125:18)
    at moduleResolve (/home/abiria/lab/seia/node_modules/.pnpm/eslint-plugin-n@16.6.2_eslint@8.57.0/node_modules/eslint-plugin-n/lib/converted-esm/import-meta-resolve.js:1181:20)
    at defaultResolve (/home/abiria/lab/seia/node_modules/.pnpm/eslint-plugin-n@16.6.2_eslint@8.57.0/node_modules/eslint-plugin-n/lib/converted-esm/import-meta-resolve.js:1261:15)
    at getFilePath (/home/abiria/lab/seia/node_modules/.pnpm/eslint-plugin-n@16.6.2_eslint@8.57.0/node_modules/eslint-plugin-n/lib/util/import-target.js:32:33)
    at new ImportTarget (/home/abiria/lab/seia/node_modules/.pnpm/eslint-plugin-n@16.6.2_eslint@8.57.0/node_modules/eslint-plugin-n/lib/util/import-target.js:150:25)
    at ExportAllDeclaration,ExportNamedDeclaration,ImportDeclaration,ImportExpression (/home/abiria/lab/seia/node_modules/.pnpm/eslint-plugin-n@16.6.2_eslint@8.57.0/node_modules/eslint-plugin-n/lib/util/visit-import.js:71:21)
    at ruleErrorHandler (/home/abiria/lab/seia/node_modules/.pnpm/eslint@8.57.0/node_modules/eslint/lib/linter/linter.js:1076:28)
    at /home/abiria/lab/seia/node_modules/.pnpm/eslint@8.57.0/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
(node:225746) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
    at tryStatSync (file:///home/abiria/lab/seia/node_modules/.pnpm/prettier@3.2.5/node_modules/prettier/index.mjs:18191:12)
    at packageResolve (file:///home/abiria/lab/seia/node_modules/.pnpm/prettier@3.2.5/node_modules/prettier/index.mjs:18774:18)
    at moduleResolve (file:///home/abiria/lab/seia/node_modules/.pnpm/prettier@3.2.5/node_modules/prettier/index.mjs:18834:20)
    at defaultResolve (file:///home/abiria/lab/seia/node_modules/.pnpm/prettier@3.2.5/node_modules/prettier/index.mjs:18921:16)
    at resolve2 (file:///home/abiria/lab/seia/node_modules/.pnpm/prettier@3.2.5/node_modules/prettier/index.mjs:18938:12)
    at importFromFile (file:///home/abiria/lab/seia/node_modules/.pnpm/prettier@3.2.5/node_modules/prettier/index.mjs:18953:16)
    at importFromDirectory (file:///home/abiria/lab/seia/node_modules/.pnpm/prettier@3.2.5/node_modules/prettier/index.mjs:23905:10)
    at importPlugin (file:///home/abiria/lab/seia/node_modules/.pnpm/prettier@3.2.5/node_modules/prettier/index.mjs:23917:12)
    at async loadPluginWithoutCache (file:///home/abiria/lab/seia/node_modules/.pnpm/prettier@3.2.5/node_modules/prettier/index.mjs:23921:18)
    at async Promise.all (index 0)
```

## Suggestion

It would be beneficial if XO uses the latest version of `eslint-plugin-n` by default so that we don't have to use deprecated APIs.

**Comment by fregante** [comment]
PR welcome

**Comment by abiriadev** [comment]
@fregante Thanks, I will make a PR soon!
